language: r
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev 
      
matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx   
      

r_check_args: --no-build-vignettes 

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

before_deploy: 
  - Rscript -e 'install.packages(c("devtools"))'
  - Rscript -e 'devtools::install()'
  
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  
