language: r
cache: packages

apt_packages:
      - libudunits2-dev 

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx   

r_check_args: --no-build-vignettes 

before_deploy: 
  - Rscript -e 'install.packages(c("devtools"))'
  - Rscript -e 'devtools::install()'
  
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true