language: r
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev 
os:
- linux

r:
- release
- devel

r_check_args: --no-build-vignettes  

before_deploy: Rscript -e 'install.packages("pkgdown")'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master