language: r
cache: packages

apt_packages:
      - libudunits2-dev 

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx   

r_check_args: --no-build-vignettes 

before_deploy: 
  - Rscript -e 'install.packages(c("devtools"))'
  - Rscript -e 'devtools::install()'
  