language: r
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev 
      
matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx   
      

r_check_args: --no-build-vignettes  

before_deploy: 
  - Rscript -e 'install.packages(c("pkgdown", "devtools"))'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    