language: r
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev 
      
matrix:
  include:
  - r: release
    os: linux
    script:
      - R CMD build . --compact-vignettes=gs+qpdf
      - R CMD check *tar.gz --as-cran 
  - r: devel
    os: linux
    script:
      - R CMD build . --compact-vignettes=gs+qpdf
      - R CMD check *tar.gz --as-cran 
  - r: release
    os: osx
    osx_image: xcode7.3
    before_install:
      - sudo tlmgr install framed titling
    script:
      - R CMD build . --compact-vignettes=gs+qpdf
      - R CMD check *tar.gz --as-cran      
      
before_deploy: 
  - Rscript -e 'install.packages(c("pkgdown", "devtools"))'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    