---
title: "data vignette"
author: "Florian D. Schneider"
date: "12 Oktober 2017"
output: html_document
---


This vignette of package traitdataform describes how to work with the data sources that have been added to this package. There are three types of data access: 

- **independent datasets** from data publications and public sources (figshare, data dryad) that are extracted and harmonized to be compliant with the trait data standard.
- **data bases** that are accessible via the package 'traits' by Scott Chamberlain and 'tr8' by Gionata Bocci and harmonized into the trait data standard. 
- **BExIS** hosts several datasets containing trait data. They can be accessed using the function ... if valid credentials can be provided. 

# TR8 

The package 'TR8' provides programmatical access to multiple databases, partly via the API of the database hosting services and partly via direct download and filtering. The package only partly harmonizes trait names. 

```{r}
library("traitdataform")
library("TR8")
my_species <- c("Salix alba","Populus nigra", "Populus alba", "Humulus lupulus")
data1 <- tr8(my_species, c("seed_wght" , "seed_mass", "seed_mas_cal", "SeedMass"))
test <- extract_traits(data1) #reformat into data.frame object
test <- sapply(test, function(x) as.numeric(as.character(x))) # turn missing values into true NA
test <- as.data.frame(test)
test$species <-  as.factor(my_species) # adds species names as an own column (not row-names)

dataset1 <- as.traitdata(test, 
                         taxa = "species",
                         traits = TR8::available_tr8$short_code
                         )

## how to maintain databse id and bibliographic reference? 

standardize.taxonomy(dataset1)

```


